spring.application.name=file-storage

server.port=9000

spring.servlet.multipart.max-file-size=3GB
spring.servlet.multipart.max-request-size=3GB

file.storage.path=${FILE_SERVER_URL:http://localhost:9000}
file.storage.key=${FILE_SERVER_API_KEY:}
